apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: qr-code-app
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 482497089777.dkr.ecr.eu-north-1.amazonaws.com/qr-code-api:latest
          ports:
            - containerPort: 8000 # Adjust to your API's port
          env:
            - name: PORT
              value: "8000"
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: qr-code-app
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 # Match this to the containerPort in api-deployment
  type: ClusterIP
