name: push docker images in ecr
on: [push]
jobs:
  push_images:
    name: push images
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: push images
        run: |
          cd source/api && make build && make push 
          cd ../frontend && make build && make push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1

  deploy_containers:
    name: apply kubernetes manifest config files
    runs-on: ubuntu-latest
    needs: push_images
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: apply kubernetes manifests
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region eu-north-1
          cd eks-cluster-cfn/k8s-manifests
          kubectl apply -f namespace.yaml
          kubectl apply -f api.yaml
          kubectl apply -f frontend.yaml
        # env:
        #   KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_REGION: eu-north-1